# Generated by Django 3.0 on 2019-12-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='status',
            new_name='is_completed',
        ),
    ]
