# Generated by Django 3.0 on 2019-12-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20191217_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
