# Generated by Django 3.0 on 2019-12-17 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20191217_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=120)),
                ('is_complete', models.BooleanField()),
                ('todos', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todos.Todos')),
            ],
        ),
    ]
