# Generated by Django 3.0 on 2019-12-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20191219_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['id'], 'verbose_name': 'Sub task'},
        ),
        migrations.AlterModelOptions(
            name='todos',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Todo'},
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='content',
            new_name='title',
        ),
    ]
